Add QR support + BIP21
PIVX-Labs/MyPIVXWallet pull request #106
Opened 2023-03-27 02:22 UTC by JSKitty

## Abstract

This PR adds a fully reusable QR module in to MPW: it's first integrated usecase being for Payment Requests, MPW now supports two kinds of QR payment requests: plain address, and BIP21, for the widest coverage ensuring MPW has compatibility with most mainstream wallets and merchants / payment gateways utilising BIP21.

![image](https://user-images.githubusercontent.com/42538664/227825037-a60e78b0-ce47-4201-933e-419ce680438e.png)

![image](https://user-images.githubusercontent.com/42538664/227824793-6da42b7b-61c0-4972-a086-e539df6b3dde.png)
*Ignore the 'Recording' icon in the right, this is not a part of the MPW UI.*

The QR module being independent and re-usable also means we can re-use this functionality incredibly easily for other usecases: like encrypted QR-based wallet exports and imports.

## What does this PR address?
It addresses the problem of having to copy/paste addresses manually by text, now, one can utilise the QR codes in both MyPIVXWallet and PIVX Core for seamless, fast transfers.

## What features or improvements were added?
A fully modular QR code reader, as well as BIP21 Payment Requests support.

## How does this benefit users?
Seamless, painless payments with minimal clicks and typing. Just a camera and some PIV.

2023-03-27 08:36 UTC, Duddino requested changes

2023-03-27 08:36 UTC, Duddino commented on scripts/misc.js
> +    // Format should match: pivx:addr[?amount=x&label=x]
We should probably check that the address contains the `pivx:` prefix

2023-03-27 08:36 UTC, Duddino commented on scripts/scanner.js
> +        try {
I think try blocks don't work on promises that you don't await, we should use `.catch()` instead

2023-03-29 08:31 UTC, Duddino submitted a review, later dismissed
tACK really like how this works

2023-04-01 18:22 UTC, JSKitty commented
Good for re-review: Shield addresses are supported now, and conflicts fixed.

2023-04-01 18:46 UTC, panleone reviewed
some comments

2023-04-01 18:46 UTC, panleone commented on scripts/misc.js
> +        !isValidBech32(strAddress).valid
then here take in input the prefix (ps mainnet ptest testnet)

2023-04-01 18:46 UTC, panleone commented on scripts/misc.js
> +export function isValidBech32(str) {
add prefix as parameter

2023-04-01 18:46 UTC, panleone commented on scripts/misc.js
> +        return { valid: true, res: bech32.decode(str) };
check that the prefix matches the one found by bech32

2023-04-01 18:46 UTC, panleone commented on scripts/global.js
> +    if (isValidBech32(cScan.data).valid) {
same here take in input the prefix

2023-04-04 10:22 UTC, BreadJS submitted a review, later dismissed

2023-04-04 10:53 UTC, panleone submitted a review, later dismissed
tACK f7e0639050db2ed6cac07af2735e9275589824e9
Sorry for the late review, finally found some time to actually test this PR!
Working as expected both for shielding and transparent + my review has been solved on discord

2023-04-04 14:56 UTC, Liquid369 submitted a review, later dismissed
tACK f7e0639050db2ed6cac07af2735e9275589824e9
Works great, even with shitty phone cameras!

2023-04-04 16:25 UTC, JSKitty commented
Conflicts resolved, pls review.

![image](https://user-images.githubusercontent.com/42538664/229856173-4fda982c-9073-4079-b819-c8620dc8fdf7.png)

2023-04-04 20:37 UTC, panleone approved these changes
retack

2023-04-04 21:27 UTC, merged