Testnet toggler now follows network state
PIVX-Labs/MyPIVXWallet pull request #152
Opened 2023-07-09 21:07 UTC by BreadJS

## What does this PR address?
When clicking on the testnet toggle in settings it was not following the network state. For example, when it failed to switch to testnet because of a loaded wallet, it still switched the toggle. This has now been fixed right now

## How does this benefit users?
The users can now see the real state of the network with the toggler.

## PIVX Address
`DDS5v6mPqUN3rdzkp3268LV7TKjHCZqy8c`

2023-07-09 21:23 UTC, JSKitty requested changes
A couple nits.

2023-07-09 21:23 UTC, JSKitty commented on scripts/global.js
> +        domTesnetToggler: document.getElementById('tesnetToggler'),
Typo: `domTesnetToggler` --> `domTestnetToggler`, the typo is consistent around the PR too.

2023-07-09 21:23 UTC, JSKitty commented on scripts/settings.js
> +    }
This code can be shortened to (keep in mind the `Tesnet` typo):
```suggestion
    doms.domTesnetToggler.checked = cChainParams.current.isTestnet;
```

2023-07-11 15:49 UTC, JSKitty approved these changes
**tACK** 566e121cab9c90347da495a30ca2c4bc14e7c315

Fixed the nits myself, LGTM before v1.0.

2023-07-11 22:09 UTC, Liquid369 approved these changes
tACK 566e121cab9c90347da495a30ca2c4bc14e7c315

2023-07-11 22:11 UTC, merged