[Refactor] Clean up wallet related code
PIVX-Labs/MyPIVXWallet pull request #200
Opened 2023-09-19 11:50 UTC by panleone

## Abstract

This is a continuation of the work started in #197 main changes are:

- From now on `Masterkey` has the only role of internally generating addresses and keys without any context, all external information, for example number of generated addresses, map of known addresses, nAccount used in derivation path has been moved to the `Wallet` class
- Having account info only stored in `Wallet` instead of spread in all files is also a first step toward multi account system.
- I  cleaned up almost all files and removed functions that should be called only internally from the Wallet class: for example `getDerivationPath()`  and `getMasterKey()`
- `Wallet` class has been decoupled from GUI
- `Network` class takes now a `Wallet` object instead of a `Masterkey`

Overall, as you can see from the `git diff`, I think that this is a good clean up and from this point we should finally be able to build a good `Wallet` class that will also manage UTXO, masternode, balance...

---

## Testing
Test all features related to wallet:
- Create a new wallet
- Check that you can send and receive funds
- Check that you can generate new addresses
- Check that the contact system works
- Check that you can encrypt the wallet and change password

If any errors are found, the PR works unexpectedly, or you have viable suggestions to improve the UX or functionality of the PR, let me know!

---
## For future contributions
While the clean up is almost completed there are still a few places that can be improved: for example

- In `bitTrx.js` there is still a call to `wallet.getDerivationPath()`
- the `Masternode` class  should also be refactored and incorporated with the new `Wallet` class

2023-09-19 12:48 UTC, Duddino requested changes
I like how the new Wallet class works, however there seems to be an exception when you open MPW, other than that I've left some minor nitpicks

2023-09-19 12:48 UTC, Duddino commented on scripts/network.js
> +import { Wallet } from './wallet.js';
```suggestion
```
Use jsdoc imports (see below)

2023-09-19 12:48 UTC, Duddino commented on scripts/network.js
> +     * @type {Wallet}
```suggestion
     * @type {import('./wallet.js').Wallet}
```

2023-09-19 12:48 UTC, Duddino commented on scripts/wallet.js
>      MasterKey,
```suggestion
```

2023-09-19 12:48 UTC, Duddino commented on scripts/wallet.js
>      MasterKey,
Import as jsdoc comment

2023-09-19 13:28 UTC, panleone commented
implemented the review and fixed the problem on opening

2023-09-19 18:04 UTC, Liquid369 submitted a review, later dismissed
tACK 893afd273ad23969f2239eea28aad1f2c886044b 
Working as per tests

2023-09-20 15:15 UTC, Duddino submitted a review, later dismissed
tACK

2023-09-20 16:04 UTC, JSKitty commented on scripts/wallet.js
> +        doms.domIdenticon.dataset.jdenticonValue = wallet.getAddress();
```suggestion
        doms.domIdenticon.dataset.jdenticonValue = await wallet.getAddress();
```

2023-09-20 19:44 UTC, panleone commented on scripts/wallet.js
> +        doms.domIdenticon.dataset.jdenticonValue = wallet.getAddress();
fixed

2023-09-20 20:51 UTC, JSKitty approved these changes
**tACK** ac66fcd654132f0c829390deb3f7bc29463f91c0

Tested every suggested Test area, tried new wallets, existing wallets, etc, not an issue.

This cleanup has gotten our wallet/key handling code in a much nicer state that I've been wanting for a while, really glad this was handled, on the way to a cleaner and more stable MPW! :rocket:

2023-09-21 09:24 UTC, Duddino approved these changes
tACK I like the new wallet class

2023-09-21 12:43 UTC, Liquid369 approved these changes
tACK ac66fcd654132f0c829390deb3f7bc29463f91c0

2023-09-21 12:45 UTC, merged