Change address v2
PIVX-Labs/MyPIVXWallet pull request #246
Opened 2023-11-02 11:03 UTC by Duddino

## Abstract
(This is a rewrite of #221)
Add proper change address, deriving them using `m/44'/119'/0'/1/${nAccount}` (or equivalent for testnet/hardware wallets).
All "internal" addresses, i.e. addresses that are not presented to the user, should derive this way.

## Testing
- Test send and receiving and that balance is correct
- (Advanced) Check that the explorer returns the correct bip32 path

2023-11-06 13:27 UTC, Liquid369 approved these changes
tACK 9ed971d9a0a9b45aab6e8285c5c56f6955261ed5
Balance fine in large testnet wallet, send/recv is fine and path shown is correct

2023-11-09 14:25 UTC, panleone requested changes
looks good apart for two things

2023-11-09 14:25 UTC, panleone commented on scripts/wallet.js
> +            for (let c = 0; c < Wallet.chains; c++) {
small optimization: instead of loading addresses for both chains, take the chain you want to load as input in `loadAddresses()`

2023-11-09 14:25 UTC, panleone commented on scripts/wallet.js
> +        const path = this.getDerivationPath(nReceiving, this.#addressIndex);
the variable #addressIndex should also distinguish between the two chains  and so you should make it a map

2023-11-13 17:04 UTC, JSKitty approved these changes
**tACK** 0563adcceca4b8cc2731dec927f9e579e1519c03, explorer looks good, External and Internal (change) chains working well, various TXs tested with various change amounts.

2023-11-13 17:22 UTC, merged