Rewrite stake tab in vue
PIVX-Labs/MyPIVXWallet pull request #325
Opened 2024-03-19 15:32 UTC by Duddino

## Abstract

Rewrite stake tab in vue

## Testing
Test that the stake functionality works

## TODO
- Write unit tests

2024-04-08 15:06 UTC, BreadJS commented
Wen merge?^-^

2024-04-10 22:29 UTC, Duddino commented
Those errors were mostly due to the two `useWallet` instances not being in sync. I've fixed it using the pinia library, which uses a very similar structure to what we were using previously, the only change code-wise is that we have to drop the `.value` when using properties from `useWallet`

2024-04-11 14:16 UTC, JSKitty commented
Upon un-delegating (straight after delegation, via internal mempool) I'm getting this `getAddress is not a function` error, presumably a change address generation issue.

```
Uncaught (in promise) TypeError: getAddress is not a function
    unstake Stake.vue:72
    callWithErrorHandling runtime-core.esm-bundler.js:195
    callWithAsyncErrorHandling runtime-core.esm-bundler.js:202
    emit runtime-core.esm-bundler.js:715
    node_modules mpw.js:10759
    submit StakeInput.vue:35
    1].rules[1]!./node_modules/vue-loader/dist/index.js??ruleSet[0].use!./scripts/stake/StakeInput.vue?vue&type=template&id=1bed7ffa/render/<.default</_cache[4 StakeInput.vue:158
    callWithErrorHandling runtime-core.esm-bundler.js:195
    callWithAsyncErrorHandling runtime-core.esm-bundler.js:202
    invoker runtime-dom.esm-bundler.js:693
```

![image](https://github.com/PIVX-Labs/MyPIVXWallet/assets/42538664/b569859f-59c1-4491-b5b9-fa5ebc1f6ec8)

2024-04-11 15:46 UTC, JSKitty commented
Staking/Unstaking is working well now it seems, balances accurate, activity displaying well, prompts look good.
Last two minor regressions I see regarding the "Set Cold Address" dialog is:
- Auto-focus was lost.
- The user no longer can give an "empty input", which used to make MPW use the Cold Pool defined in chainparams; it's slightly more difficult to return to the default address now.

After this I think we're ready for Quality Control.

2024-04-11 15:49 UTC, JSKitty commented
Found a niche bug, with "Advanced Mode" enabled, trying to set a custom Owner Address from a Contact (mouse on button) results in this:

```
Uncaught (in promise) TypeError: domInput is undefined
    guiSelectContact contacts-book.js:286
    onclick 
```

![image](https://github.com/PIVX-Labs/MyPIVXWallet/assets/42538664/52dcb3d4-8e01-479d-bef7-ad8864915be2)

2024-04-12 13:57 UTC, JSKitty submitted a review, later dismissed
**tACK** 9f0c15c2413177518358c6daf52698520a527ebc

Pushing to Quality Control, confident in the PR's stability at this point.

2024-04-12 21:32 UTC, JSKitty commented
> Found a niche bug, with "Advanced Mode" enabled, trying to set a custom Owner Address from a Contact (mouse on button) results in this:
> 
> ```
> Uncaught (in promise) TypeError: domInput is undefined
>     guiSelectContact contacts-book.js:286
>     onclick 
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/42538664/321697277-52dcb3d4-8e01-479d-bef7-ad8864915be2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI5NTY5NTEsIm5iZiI6MTcxMjk1NjY1MSwicGF0aCI6Ii80MjUzODY2NC8zMjE2OTcyNzctNTJkY2IzZDQtOGUwMS00NzlkLWJlZjctYWQ4ODY0OTE1YmUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEyVDIxMTczMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRkYTUwYWFmMzQ2ZDAxYTk2NjMyYzZkNTUxMDkxNjgwNGE4MDE3YTkyNjA4OTQyNmMzNzM1NTJjMTNmNmFjNzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rRFXcoKzg_CjUyMctRse9hHHqFqi6cfrNrL08B9Kk48)

Relevant to this niche issue: I noticed the Stake dialog (advanced Owner Address) after clicking or typing a Contact's name, cannot send the transaction as the Name is not being converted to the Address it's associated to, for this, you can use the same name->address lookup that the normal Send flow uses.

2024-04-15 14:32 UTC, JSKitty requested changes

2024-04-16 08:31 UTC, panleone requested changes

2024-04-16 08:31 UTC, panleone commented on scripts/wallet.js
> +                await getNetwork().getLatestTxs(this);
getLatestTxs must not be called anymore after first sync
`await this.getLatestBlocks(block);` will handle both

2024-04-16 14:50 UTC, JSKitty submitted a review, later dismissed
**tACK** bbe36d1c2c1a1706e5dfe2ea621fb1b679eb79f9

LGTM, just a few logs to nuke then we should merge this ASAP.

2024-04-16 14:50 UTC, JSKitty commented on scripts/composables/use_wallet.js
> +        console.log(r);
Nuke

2024-04-16 14:50 UTC, JSKitty commented on scripts/parsed_secret.js
> +        // createAlert('warning', ALERTS.FAILED_TO_IMPORT + '<br>', 6000);
Nuke? I assume callers of `parse` will handle any `null` return notifications.

2024-04-16 14:50 UTC, JSKitty commented on scripts/stake/Stake.vue
> +    console.log(returnAddress, ownerAddress);
Nuke

2024-04-16 14:50 UTC, JSKitty commented on scripts/stake/StakeInput.vue
> +    console.log(ownerAddress.value);
Nuke

2024-04-16 14:50 UTC, JSKitty commented on scripts/stake/StakeInput.vue
> +    console.log(ownerAddress.value);
Nuke

2024-04-16 17:28 UTC, JSKitty approved these changes
**re-tACK**

2024-04-16 18:14 UTC, panleone approved these changes
tACK d77c2372ac3268bfe787c2a93ba1c63841bfca33

2024-04-16 19:54 UTC, merged