switch to websockets
PIVX-Labs/MyPIVXWallet pull request #358
Opened 2024-04-26 15:59 UTC by panleone

## Abstract

Replace the legacy HTTP requests bases system with a websocket implementation.

TODO list:

- in case of disconnection try to reconnect
- we need to have all explorers updated to Duddino's version or some websocket calls are unsupported!
- clean up some parts of the code

---

## Testing

Connect to Duddino's mainnet explorer and verify that everything is still working as before

2024-07-31 09:22 UTC, Duddino requested changes

2024-07-31 09:22 UTC, Duddino commented on scripts/network.js
> +    }
Use onopen event

2024-07-31 09:22 UTC, Duddino commented on scripts/network.js
> +        const maxAwaitTime = 600 * 1000;
We shouldn't have a maxAwaitTime, we should only abort if the websocket closes

2024-11-04 11:54 UTC, panleone commented
Closing as stale + needs rebase with the new network model #431.

Not a priority since Websockets would be a good optimization only transparent sync (for shield sync we have #430 which is even faster...).

2024-11-04 11:54 UTC, closed without merging