Cache and prefetch shield files
PIVX-Labs/MyPIVXWallet pull request #365
Opened 2024-05-02 14:06 UTC by Duddino

## Abstract

When creating or loading a shield wallet, a bunch of helper scripts are fetched from the server sequentially. This happens one time for each thread.
Even though they're cached, a request is still sent to the server to see if the file changed, this creates a noticeable between creating a wallet and getting to the dashboard, particularly on machines with a high number of cores, and/or with a high network latency.

This PR aims to prefetch the required shield files, before they're actually needed. The idea is that by the time someone has created and backed up their seedphrase, the browser would have already fetched the files.
Additionally, this PR adds the util scripts each worker needs in the sapling cache to avoid contacting the server for each worker.

## Testing
- Have a third world connection (or simulate it using the devtools)
- Open MPW and try to create a new wallet or import an existing one, and see if there is any noticeable lag

2024-05-03 15:12 UTC, panleone requested changes
nice PR

2024-05-03 15:12 UTC, panleone commented on scripts/native-worker.js
> +    console.log(event.data);
remove this console.log

2024-05-03 15:12 UTC, panleone commented on scripts/native-worker.js
> +    console.log(files);
remove this console.log

2024-05-06 16:49 UTC, panleone approved these changes
tACK e6191beeb534c4fdb4cf9f08e431d48d5ec8d563

2024-05-06 21:02 UTC, JSKitty requested changes
Receiving error after simply opening the page, Firefox on Linux.

```
Uncaught (in promise) TypeError: registration.active is null
    registerWorker native.js:15
```

![image](https://github.com/PIVX-Labs/MyPIVXWallet/assets/42538664/ba429b1f-646e-4ec2-8179-e516a816fd89)

2024-07-19 07:54 UTC, panleone approved these changes
tACK b3c1e7e354eb2c4d39a1f449293e25c2ebe83f16

noticeably faster than the master branch

2024-07-26 16:19 UTC, JSKitty approved these changes
**tACK** c71fed46876d1926532af903f767db4f8d5d4656

Took a few attempts for my configuration, but undeniably faster loading speed now. Happy this was taken care of. 🙏

2024-07-27 06:42 UTC, merged