Hindi Translation done
PIVX-Labs/MyPIVXWallet pull request #379
Opened 2024-08-22 18:00 UTC by RushaliPadhiary

It has the hindi translation for the Wallet app

2024-08-23 12:13 UTC, Duddino requested changes
Need to escape some quotes

2024-08-23 12:13 UTC, Duddino commented on locale/hi/translation.toml
> +encryptFirstForContacts = "जब आप डैशबोर्ड में "{button}" पर क्लिक करते हैं, तो आप PIV प्राप्त करना आसान बनाने के लिए एक संपर्क बना सकते हैं!" # Once you hit \"{button}\" in the Dashboard, you can cre
```suggestion
encryptFirstForContacts = "जब आप डैशबोर्ड में \"{button}\" पर क्लिक करते हैं, तो आप PIV प्राप्त करना आसान बनाने के लिए एक संपर्क बना सकते हैं!" # Once you hit \"{button}\" in the Dashboard, you can create a Contact to make receiving PIV easier!
```

2024-08-23 12:13 UTC, Duddino commented on locale/hi/translation.toml
> +addContactWarning = "सुनिश्चित करें कि यह असली "{strName}" है, अज्ञात स्रोतों से संपर्क अनुरोध स्वीकार न करें!" # Ensure that this is the real \"{strName}\", do not accept Contact requests from unkno
```suggestion
addContactWarning = "सुनिश्चित करें कि यह असली \"{strName}\" है, अज्ञात स्रोतों से संपर्क अनुरोध स्वीकार न करें!" # Ensure that this is the real \"{strName}\", do not accept Contact requests from unknown sources!
```

2024-08-23 12:13 UTC, Duddino commented on locale/hi/translation.toml
> +editContactTitle = ""{strName}" संपर्क बदलें" # Change \"{strName}\" Contact
```suggestion
editContactTitle = "\"{strName}\" संपर्क बदलें" # Change \"{strName}\" Contact
```

2024-08-23 12:13 UTC, Duddino commented on locale/hi/translation.toml
> +popupProposalEncryptFirst = "आपको प्रपोजल बनाने से पहले "{button}" पर क्लिक करना होगा!" # You need to hit "{button}" before you can create proposals!
```suggestion
popupProposalEncryptFirst = "आपको प्रपोजल बनाने से पहले \"{button}\" पर क्लिक करना होगा!" # You need to hit "{button}" before you can create proposals!
```

2024-08-23 12:13 UTC, Duddino commented on locale/hi/translation.toml
> +CONTACTS_ENCRYPT_FIRST = "आपको संपर्कों का उपयोग करने से पहले "{button}" पर क्लिक करना होगा!" # You need to hit "{button}" before you can use Contacts!
```suggestion
CONTACTS_ENCRYPT_FIRST = "आपको संपर्कों का उपयोग करने से पहले \"{button}\" पर क्लिक करना होगा!" # You need to hit "{button}" before you can use Contacts!
```

2024-08-23 12:13 UTC, Duddino commented on locale/hi/translation.toml
> +CONTACTS_EDIT_NAME_ALREADY_EXISTS = "<b>संपर्क पहले से मौजूद है!</b><br>एक संपर्क पहले से ही "{strNewName}" के नाम से है!" # <b>Contact already exists!</b><br>A contact is already called "{strNewName
```suggestion
CONTACTS_EDIT_NAME_ALREADY_EXISTS = "<b>संपर्क पहले से मौजूद है!</b><br>एक संपर्क पहले से ही \"{strNewName}\" के नाम से है!" # <b>Contact already exists!</b><br>A contact is already called "{strNewName}"!
```

2024-08-23 12:13 UTC, Duddino commented on locale/hi/translation.toml
> +CONFIRM_LEDGER_TX_OUT = "आप {value} {ticker} को <div class="inline-address">{address}</div> भेजेंगे" # You will send {value} {ticker} to <div class="inline-address">{address}</div>
```suggestion
CONFIRM_LEDGER_TX_OUT = "आप {value} {ticker} को <div class=\"inline-address\">{address}</div> भेजेंगे" # You will send {value} {ticker} to <div class="inline-address">{address}</div>
```

2024-08-23 12:16 UTC, Duddino requested changes
You need to add the language to `arrActiveLangs` in `i18n.js`

2024-08-26 11:59 UTC, JSKitty approved these changes
**tACK** 4e4ac2a50ecd7d5015f56387072228f8abbc5d56

We'll update these translations for any new strings added and/or changed prior to v2.0 launch.

2024-08-30 15:58 UTC, merged