Refactor some stuff
PIVX-Labs/MyPIVXWallet pull request #428
Opened 2024-10-14 14:35 UTC by panleone

## Abstract
A bit of refactor, I suggest to review commit by commit

- first commit: remove the wallet from the network constructor;
- second commit:  add a `use_network.js` class, intermediate between VUE and .js logic
- third commit: use the new composable class in place of importing the global network class
- fourth commit: clean up unused imports and a function in global.js
- fifth commit: get rid of the global block count in `Activity.js`

---

2024-10-15 11:39 UTC, Duddino reviewed
other than that nit should be good to merge

2024-10-15 11:39 UTC, Duddino commented on scripts/composables/use_network.js
> +    const explorerUrl = ref('');
Either watch the variable and change explorer or set is as read only.

2024-10-15 14:04 UTC, JSKitty requested changes
`openExplorer` was used by the Governance Tab for opening addresses, it'll need replacing with something (until `use_network.js` can be used with Duddino's Vue Governance port)

![image](https://github.com/user-attachments/assets/6ac33e2b-5011-4f58-8047-494bab18c53b)

2024-10-16 06:15 UTC, panleone commented
> `openExplorer` was used by the Governance Tab for opening addresses, it'll need replacing with something (until `use_network.js` can be used with Duddino's Vue Governance port)
> 
> ![image](https://private-user-images.githubusercontent.com/42538664/376646345-6ac33e2b-5011-4f58-8047-494bab18c53b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwNTk1NzcsIm5iZiI6MTcyOTA1OTI3NywicGF0aCI6Ii80MjUzODY2NC8zNzY2NDYzNDUtNmFjMzNlMmItNTAxMS00ZjU4LTgwNDctNDk0YmFiMThjNTNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE2VDA2MTQzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc0YjFmNDQwY2I1OGQ5YTlhNWI4YzNhZTc5MmVlZDc3ZTA1ZjVkODc1YzA1N2MxYjI0NmZhYTQ0NWY5NTkyMmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.giXX5wacIvZIuW3_asn8mafms4cGXC3aVaAsM_0LyWY)

nice catch, I don't know why I thought it was unused

2024-10-16 14:32 UTC, JSKitty approved these changes
**tACK** 1edef671989e37d6e80bf515b4e4161f6de89202

Good little refactor.

2024-10-17 20:40 UTC, merged