Notification revamp
PIVX-Labs/MyPIVXWallet pull request #468
Opened 2024-11-18 10:15 UTC by BreadJS

## Abstract

As planned, the request to revamp the notifications to give it a better look and better interface for users to interact with.

2024-11-19 16:01 UTC, panleone requested changes
code looks good and works as expected. My only comment is that unit tests should be updated

2024-11-19 16:01 UTC, panleone commented on tests/unit/alert.spec.js
> +        expect(createAlertSpy).toHaveBeenCalledWith(
Improve unit test coverage by testing the two new fields
```
actionName,
actionFunc,
```

2024-11-20 12:15 UTC, panleone submitted a review, later dismissed
tACK 6aea10e46b81014f00a1bd8f49a7260378a293fe

2024-11-26 13:14 UTC, Duddino approved these changes
tACK, with a very minor nit

2024-11-26 13:14 UTC, Duddino commented on scripts/alerts/Alert.vue
> +        ></div>
```suggestion
        >{{notificationCount}}</div>
```

2024-11-26 13:24 UTC, merged